//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class luGrant
    {
        public int Id { get; set; }
        public int UserGroupId { get; set; }
        public int ActivityId { get; set; }
    
        public virtual luUserActivity luUserActivity { get; set; }
        public virtual luUserGroup luUserGroup { get; set; }
    }
}
