//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pesEntities : DbContext
    {
        public pesEntities()
            : base("name=pesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<luAccountStatu> luAccountStatus { get; set; }
        public virtual DbSet<luGrant> luGrants { get; set; }
        public virtual DbSet<luUserActivity> luUserActivities { get; set; }
        public virtual DbSet<luUserGroup> luUserGroups { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<luDocumentStatu> luDocumentStatus { get; set; }
        public virtual DbSet<luCustomerType> luCustomerTypes { get; set; }
        public virtual DbSet<luDocumentType> luDocumentTypes { get; set; }
        public virtual DbSet<luPropertyType> luPropertyTypes { get; set; }
        public virtual DbSet<luValuationPurpose> luValuationPurposes { get; set; }
        public virtual DbSet<UploadedDocument> UploadedDocuments { get; set; }
        public virtual DbSet<EstimationRequest> EstimationRequests { get; set; }
    }
}
