//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UploadedDocument
    {
        public int Id { get; set; }
        public int EstimationRequestId { get; set; }
        public int DocumentTypeId { get; set; }
        public string FilePath { get; set; }
        public string Remark { get; set; }
    
        public virtual luDocumentType luDocumentType { get; set; }
        public virtual EstimationRequest EstimationRequest { get; set; }
    }
}
