//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.EstimationRequests = new HashSet<EstimationRequest>();
            this.EstimationRequests1 = new HashSet<EstimationRequest>();
            this.EstimationRequests2 = new HashSet<EstimationRequest>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public int UserGroup { get; set; }
        public string Division { get; set; }
        public int AccountStatus { get; set; }
    
        public virtual luAccountStatu luAccountStatu { get; set; }
        public virtual luUserGroup luUserGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstimationRequest> EstimationRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstimationRequest> EstimationRequests1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstimationRequest> EstimationRequests2 { get; set; }
    }
}
